#!/usr/bin/env node
// Build script: matches collection data to Rebrickable thumbnails and outputs data.json

const fs = require('fs');
const path = require('path');

const REBRICKABLE_CSV = '/Users/jeffutzman/Library/Group Containers/group.com.apple.coreservices.useractivityd/shared-pasteboard/items/6D01208A-F89B-4E1B-88D2-839167B4DDA4/minifigs.csv';

// --- Collection data from Google Sheet ---
const collection = [
  { name: "Caveman", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Cheerleader", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Circus Clown", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Cowboy", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Deep Sea Diver", itemNum: "8683", series: "Series 1", collected: true },
  { name: "Demolition Dummy", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Forestman", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Magician", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Ninja", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Nurse", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Robot", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Skater", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Spaceman", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Super Wrestler", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Tribal hunter", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Zombie", itemNum: "8683", series: "Series 1", collected: false },
  { name: "Disco Dude", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Explorer", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Karate Master", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Lifeguard", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Maraca Man", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Mime", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Pharaoh", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Pop Star", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Ringmaster", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Skier", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Spartan Warrior", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Surfer", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Traffic Cop", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Vampire", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Weight Lifter", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Witch", itemNum: "8684", series: "Series 2", collected: false },
  { name: "Hula Dancer", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Tribal Chief", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Samurai Warrior", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Tennis Player", itemNum: "8803", series: "Series 3", collected: true },
  { name: "Sumo Wrestler", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Baseball Player", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Fisherman", itemNum: "8803", series: "Series 3", collected: true },
  { name: "Elf", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Rapper", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Space Alien", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Gorilla Suit Guy", itemNum: "8803", series: "Series 3", collected: true },
  { name: "Race Car Driver", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Mummy", itemNum: "8803", series: "Series 3", collected: true },
  { name: "Snowboarder", itemNum: "8803", series: "Series 3", collected: true },
  { name: "Space Villain", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Pilot", itemNum: "8803", series: "Series 3", collected: false },
  { name: "Artist", itemNum: "8804", series: "Series 4", collected: true },
  { name: "Crazy Scientist", itemNum: "8804", series: "Series 4", collected: true },
  { name: "Hazmat Guy", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Hockey Player", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Ice Skater", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Kimono Girl", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Lawn Gnome", itemNum: "8804", series: "Series 4", collected: false },
  { name: "The Monster", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Musketeer", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Punk Rocker", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Sailor", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Street Skater", itemNum: "8804", series: "Series 4", collected: true },
  { name: "Soccer Player", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Surfer Girl", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Viking", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Werewolf", itemNum: "8804", series: "Series 4", collected: false },
  { name: "Boxer", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Cave Woman", itemNum: "8805", series: "Series 5", collected: true },
  { name: "Detective", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Egyptian Queen", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Evil Dwarf", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Fitness Instructor", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Gangster", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Gladiator", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Graduate", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Lizard Man", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Lumberjack", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Ice Fisherman", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Royal Guard", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Small Clown", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Snowboarder Guy", itemNum: "8805", series: "Series 5", collected: false },
  { name: "Zookeeper", itemNum: "8805", series: "Series 5", collected: true },
  { name: "Bandit", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Butcher", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Classic Alien", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Clockwork Robot", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Genie", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Flamenco Dancer", itemNum: "8827", series: "Series 6", collected: true },
  { name: "Highland Battler", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Intergalactic Girl", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Lady Liberty", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Leprechaun", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Mechanic", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Minotaur", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Roman Soldier", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Skater Girl", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Sleepyhead", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Surgeon", itemNum: "8827", series: "Series 6", collected: false },
  { name: "Aztec Warrior", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Bagpiper", itemNum: "8831", series: "Series 7", collected: true },
  { name: "Bride", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Bunny Suit Guy", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Computer Programmer", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Daredevil", itemNum: "8831", series: "Series 7", collected: true },
  { name: "Evil Knight", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Galaxy Patrol", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Grandma Visitor", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Hippie", itemNum: "8831", series: "Series 7", collected: true },
  { name: "Jungle Boy", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Ocean King", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Rocker Girl", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Swimming Champion", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Tennis Ace", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Viking Woman", itemNum: "8831", series: "Series 7", collected: false },
  { name: "Evil Robot", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Conquistador", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Lederhosen Guy", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Cowgirl", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Football Player", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Diver", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Downhill Skier", itemNum: "8833", series: "Series 8", collected: true },
  { name: "Businessman", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Fairy", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Santa", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Vampire Bat", itemNum: "8833", series: "Series 8", collected: false },
  { name: "DJ", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Red Cheerleader", itemNum: "8833", series: "Series 8", collected: false },
  { name: "The Thespian", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Pirate Captain", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Alien Villainess", itemNum: "8833", series: "Series 8", collected: false },
  { name: "Waiter", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Cyclops", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Hollywood Starlet", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Heroic Knight", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Roman Emperor", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Policeman", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Chicken Suit Guy", itemNum: "71000", series: "Series 9", collected: true },
  { name: "Roller Derby Girl", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Fortune Teller", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Judge", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Alien Avenger", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Mermaid", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Battle Mech", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Mr. Good and Evil", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Forest Maiden", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Plumber", itemNum: "71000", series: "Series 9", collected: false },
  { name: "Librarian", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Medusa", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Roman Commander", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Warrior Woman", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Tomahawk Warrior", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Skydiver", itemNum: "71001", series: "Series 10", collected: true },
  { name: "Bumblebee Girl", itemNum: "71001", series: "Series 10", collected: true },
  { name: "Grandpa", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Paintballer", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Sea Captain", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Sad Clown", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Revolutionary Soldier", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Baseball Fielder", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Trendsetter", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Decorator", itemNum: "71001", series: "Series 10", collected: true },
  { name: "Motorcycle Mechanic", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Mr. Gold", itemNum: "71001", series: "Series 10", collected: false },
  { name: "Yeti", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Evil Mech", itemNum: "71002", series: "Series 11", collected: true },
  { name: "Welder", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Lady Robot", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Saxophone Player", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Constable", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Holiday Elf", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Pretzel Girl", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Scarecrow", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Mountain Climber", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Grandma", itemNum: "71002", series: "Series 11", collected: true },
  { name: "Island Warrior", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Gingerbread Man", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Barbarian", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Diner Waitress", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Scientist", itemNum: "71002", series: "Series 11", collected: false },
  { name: "Space Miner", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Battle Goddess", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Wizard", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Dino Tracker", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Swashbuckler", itemNum: "71007", series: "Series 12", collected: true },
  { name: "Jester", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Piggy Guy", itemNum: "71007", series: "Series 12", collected: true },
  { name: "Hun Warrior", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Fairytale Princess", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Pizza Delivery Man", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Video Game Guy", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Spooky Girl", itemNum: "71007", series: "Series 12", collected: true },
  { name: "Prospector", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Genie Girl", itemNum: "71007", series: "Series 12", collected: true },
  { name: "Rock Star", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Lifeguard", itemNum: "71007", series: "Series 12", collected: false },
  { name: "Galaxy Trooper", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Alien Trooper", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Evil Wizard", itemNum: "71008", series: "Series 13", collected: false },
  { name: "King", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Goblin", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Lady Cyclops", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Snake Charmer", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Paleontologist", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Carpenter", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Hot Dog Guy", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Sheriff", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Samurai", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Disco Diva", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Unicorn Girl", itemNum: "71008", series: "Series 13", collected: false },
  { name: "Fencer", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Egyptian Warrior", itemNum: "71008", series: "Series 13", collected: true },
  { name: "Monster Scientist", itemNum: "71010", series: "Series 14", collected: true },
  { name: "Monster Rocker", itemNum: "71010", series: "Series 14", collected: true },
  { name: "Zombie Businessman", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Plant Monster", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Skeleton Guy", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Tiger Woman", itemNum: "71010", series: "Series 14", collected: true },
  { name: "Spider Lady", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Wolf Guy", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Wacky Witch", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Zombie Cheerleader", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Zombie Pirate", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Fly Monster", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Gargoyle", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Banshee", itemNum: "71010", series: "Series 14", collected: true },
  { name: "Spectre", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Square Foot", itemNum: "71010", series: "Series 14", collected: false },
  { name: "Farmer", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Faun", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Tribal Woman", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Shark Suit Guy", itemNum: "71011", series: "Series 15", collected: true },
  { name: "Queen", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Animal Control", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Jewel Thief", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Ballerina", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Flying Warrior", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Frightening Knight", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Wrestling Champion", itemNum: "71011", series: "Series 15", collected: true },
  { name: "Clumsy Guy", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Kendo Fighter", itemNum: "71011", series: "Series 15", collected: true },
  { name: "Astronaut", itemNum: "71011", series: "Series 15", collected: true },
  { name: "Laser Mech", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Janitor", itemNum: "71011", series: "Series 15", collected: false },
  { name: "Ice Queen", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Cute Little Devil", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Spooky Boy", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Babysitter", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Spy", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Banana Guy", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Mariachi", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Penguin Boy", itemNum: "71013", series: "Series 16", collected: true },
  { name: "Wildlife Photographer", itemNum: "71013", series: "Series 16", collected: true },
  { name: "Kickboxer", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Rogue", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Cyborg", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Hiker", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Desert Warrior", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Scallywag Pirate", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Dog Show Winner", itemNum: "71013", series: "Series 16", collected: false },
  { name: "Pro Surfer", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Gourmet Chef", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Hot Dog Vendor", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Elf Maiden", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Circus Strongman", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Yuppie", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Veterinarian", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Connoisseur", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Butterfly Girl", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Roman Gladiator", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Corn Cob Guy", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Retro Space Hero", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Dance Instructor", itemNum: "71018", series: "Series 17", collected: true },
  { name: "Battle Dwarf", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Rocket Boy", itemNum: "71018", series: "Series 17", collected: false },
  { name: "Highwayman", itemNum: "71018", series: "Series 17", collected: false },
  { name: "LEGO Brick Suit Guy", itemNum: "71021", series: "Series 18", collected: true },
  { name: "1978 Police Officer", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Elephant Costume Girl", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Firework Guy", itemNum: "71021", series: "Series 18", collected: true },
  { name: "Dragon Suit Guy", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Cake Guy", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Race Car Guy", itemNum: "71021", series: "Series 18", collected: true },
  { name: "Flowerpot Girl", itemNum: "71021", series: "Series 18", collected: false },
  { name: "LEGO Brick Suit Girl", itemNum: "71021", series: "Series 18", collected: true },
  { name: "Unicorn Guy", itemNum: "71021", series: "Series 18", collected: true },
  { name: "Birthday Party Boy", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Spider Suit Boy", itemNum: "71021", series: "Series 18", collected: true },
  { name: "Birthday Party Girl", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Cactus Girl", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Cowboy Costume Guy", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Party Clown", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Cat Costume Girl", itemNum: "71021", series: "Series 18", collected: false },
  { name: "Gamer", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Shower Guy", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Ghost Knight", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Monkey King", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Programmer", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Mummy", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Jungle Explorer", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Firefighter", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Dog Carer", itemNum: "71025", series: "Series 19", collected: true },
  { name: "Pizza Guy", itemNum: "71025", series: "Series 19", collected: true },
  { name: "Space Bounty Hunter", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Gardener", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Rugby Player", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Fox Suit Girl", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Bear Costume Guy", itemNum: "71025", series: "Series 19", collected: false },
  { name: "Mountain Biker", itemNum: "71025", series: "Series 19", collected: false },
  { name: "80s Musician", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Athlete", itemNum: "71027", series: "Series 20", collected: true },
  { name: "Breakdancer", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Brick Costume Boy", itemNum: "71027", series: "Series 20", collected: true },
  { name: "Drone Boy", itemNum: "71027", series: "Series 20", collected: true },
  { name: "Llama Costume Girl", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Martial Arts Boy", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Pea Pod Costume Girl", itemNum: "71027", series: "Series 20", collected: true },
  { name: "Pinata Boy", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Pirate Girl", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Pajama Girl", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Sea Rescuer", itemNum: "71027", series: "Series 20", collected: true },
  { name: "Space Fan", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Super Warrior", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Tournament Knight", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Viking", itemNum: "71027", series: "Series 20", collected: false },
  { name: "Airplane Girl", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Alien", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Ancient Warrior", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Beekeeper", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Cabaret Singer", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Centaur Warrior", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Ladybug Girl", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Paddle Surfer", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Pug Costume Guy", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Shipwreck Survivor", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Space Police Guy", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Violin Kid", itemNum: "71029", series: "Series 21", collected: true },
  { name: "Birdwatcher", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Chili Costume Fan", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Figure Skating Champion", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Forest Elf", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Horse and Groom", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Night Protector", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Raccoon Costume Fan", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Robot Repair Tech", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Snow Guardian", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Space Creature", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Troubadour", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Wheelchair Racer", itemNum: "71032", series: "Series 22", collected: true },
  { name: "Cardboard Robot", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Holiday Elf", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Ferry Captain", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Green Dragon Costume", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Knight of the Yellow Castle", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Nutcracker", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Popcorn Costume", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Reindeer Costume", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Snowman", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Sugar Fairy", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Turkey Costume", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Wolf Costume", itemNum: "71034", series: "Series 23", collected: true },
  { name: "Brown Astronaut and Spacebaby", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Carrot Mascot", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Conservationist", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Falconer", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Football Referee", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Newspaper Kid", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Orc", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Potter", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Robot Warrior", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Rockin' Horse Rider", itemNum: "71037", series: "Series 24", collected: true },
  { name: "Rococo Aristocrat", itemNum: "71037", series: "Series 24", collected: true },
  { name: "T-Rex Costume Fan", itemNum: "71037", series: "Series 24", collected: true },
  { name: "E-Sports Gamer", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Mushroom Sprite", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Pet Groomer", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Film Noir Detective", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Train Kid", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Triceratops Costume Fan", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Goatherd", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Fitness Instructor", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Sprinter", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Fierce Barbarian", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Vampire Knight", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Harpy", itemNum: "71045", series: "Series 25", collected: true },
  { name: "Alien Beetlezoid", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Alien Tourist", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Blacktron Mutant", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Flying Saucer Costume Fan", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Ice Planet Explorer", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Imposter", itemNum: "71046", series: "Series 26", collected: true },
  { name: "M-Tron Powerlifter", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Nurse Android", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Orion", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Retro Space Heroine", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Robot Butler", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Spacewalking Astronaut", itemNum: "71046", series: "Series 26", collected: true },
  { name: "Hamster Costume Fan", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Wolfpack Beastmaster", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Jetpack Racer", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Astronomer Kid", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Plush Toy Collector", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Longboarder", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Pterodactyl Costume Fan", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Bogeyman", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Cupid", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Pirate Quartermaster", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Cat Lover", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Steampunk Inventor", itemNum: "71048", series: "Series 27", collected: true },
  { name: "Peacock", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Fluffy Cat", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Goldfish", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Monkey", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Frog", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Koala", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Dalmatian", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Crocodile", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Dolphin", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Cute Bunny", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Lion", itemNum: "71051", series: "Series 28", collected: true },
  { name: "Parrot", itemNum: "71051", series: "Series 28", collected: true },
];

// --- Parse Rebrickable CSV ---
function parseCSV(text) {
  const lines = text.split('\n');
  const headers = lines[0].split(',');
  return lines.slice(1).map(line => {
    // Handle quoted fields
    const fields = [];
    let current = '';
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      if (line[i] === '"') {
        inQuotes = !inQuotes;
      } else if (line[i] === ',' && !inQuotes) {
        fields.push(current.trim());
        current = '';
      } else {
        current += line[i];
      }
    }
    fields.push(current.trim());
    const obj = {};
    headers.forEach((h, i) => obj[h.trim()] = fields[i] || '');
    return obj;
  }).filter(r => r.fig_num);
}

function normalize(str) {
  return (str || '').toLowerCase()
    .replace(/\(cmf\)/gi, '')
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const rebrickableText = fs.readFileSync(REBRICKABLE_CSV, 'utf8');
const rebrickable = parseCSV(rebrickableText);

// Build normalized lookup
const lookup = new Map();
for (const fig of rebrickable) {
  const key = normalize(fig.name);
  if (!lookup.has(key)) lookup.set(key, fig);
}

// Manual overrides for tricky name mismatches
const manualOverrides = {
  'Tribal hunter': 'Tribal Hunter',
  'Snowboarder': 'Snowboarder (CMF)',
  'Snowboarder Guy': 'Snowboarder Guy',
  'Vampire': 'Vampire (CMF)',
  'Vampire Bat': 'Vampire Bat',
  'Mummy': 'Mummy (CMF)',
  'Dino tracker': 'Dino Tracker',
  'Evil mech': 'Evil Mech',
  'Pretzel Elf': 'Pretzel Girl',
  'Holiday elf': 'Holiday Elf',
  'Lederhosen': 'Lederhosen Guy',
  '80s Musician': "80's Musician",
  'Hot Dog Guy': 'Hot Dog Man',
  'Lifeguard': 'Lifeguard (CMF)',
  'Rouge': 'Rogue (Minifigures)',
  'Rogue': 'Rogue',
  'King': 'Classic King',
  'Fitness Instructor': 'Fitness Instructor (CMF)',
  'Brown Astronaut and Spacebaby': 'Brown Astronaut and Spacebaby',
  'Green Dragon Costume': 'Dragon Costume - Green',
  '1978 Police Officer': 'Classic Police Officer',
  'Dog Carer': 'Dog Sitter',
};

// Find best match in rebrickable for a collection entry
function findImage(fig) {
  const searchName = manualOverrides[fig.name] || fig.name;
  const key = normalize(searchName);

  // Exact match first
  if (lookup.has(key)) return lookup.get(key).img_url;

  // Try substring match
  for (const [k, v] of lookup) {
    if (k === key) return v.img_url;
  }

  // Try if rebrickable name contains the search name as a substring
  for (const [k, v] of lookup) {
    if (k.includes(key) || key.includes(k)) return v.img_url;
  }

  console.warn(`  NO MATCH: "${fig.name}" (series: ${fig.series})`);
  return null;
}

console.log('Matching minifigs to Rebrickable images...');
const unmatched = [];
const result = collection.map(fig => {
  const img = findImage(fig);
  if (!img) unmatched.push(`${fig.series}: ${fig.name}`);
  return { ...fig, img };
});

if (unmatched.length) {
  console.log(`\nUnmatched (${unmatched.length}):`);
  unmatched.forEach(u => console.log(' -', u));
}

const matched = result.filter(f => f.img).length;
console.log(`\nMatched ${matched}/${result.length} minifigs`);

fs.writeFileSync(
  path.join(__dirname, 'data.json'),
  JSON.stringify(result, null, 2)
);
console.log('Written to data.json');
